In [9]:
import pandas as pd
import sqlite3

 
con = sqlite3.connect("C:\\Users\\jazee\\OneDrive\\Desktop\\ipl-cricket-analytics\\data\\raw\\ipl.db") 
  
def q(sql): 
    """Run a SELECT and show the result as a table.""" 
    return pd.read_sql(sql, con)


def run_sql_file(path): 
    """Read a .sql file and execute every statement in it.""" 
    with open(path, 'r') as f: 
        script = f.read() 
    con.executescript(script) 
    con.commit() 
    print('ran', path)

In [10]:
q("SELECT * FROM v_ball LIMIT 10;")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
5,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,5,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
6,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,6,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
7,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,0,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
8,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,1,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0
9,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,2,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0

In [14]:
# Cell 1 — Display all data from v_ball

query = """
SELECT *
FROM v_ball
LIMIT 10;
"""

df = pd.read_sql_query(query, con)
df

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
5,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,5,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
6,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,6,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
7,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,0,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
8,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,1,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0
9,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,2,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0

In [18]:
# Cell 2 — Display all innings data
# v_innings does not exist in your database, so we create the innings result directly.

query = """
SELECT
    match_id,
    innings,
    batting_team,
    SUM(total_runs) AS runs,
    SUM(is_legal) AS legal_balls,
    SUM(is_wicket) AS wickets
FROM v_ball
GROUP BY match_id, innings, batting_team
ORDER BY match_id, innings
LIMIT 10;
"""

df = pd.read_sql_query(query, con)
df

   match_id  innings                 batting_team  runs  legal_balls  wickets
0    335982        1        Kolkata Knight Riders   222          120        3
1    335982        2  Royal Challengers Bangalore    82           91       10
2    335983        1          Chennai Super Kings   240          120        5
3    335983        2                 Punjab Kings   207          120        4
4    335984        1             Rajasthan Royals   129          120        8
5    335984        2               Delhi Capitals   132           91        1
6    335985        1               Mumbai Indians   165          120        7
7    335985        2  Royal Challengers Bangalore   166          118        5
8    335986        1          Sunrisers Hyderabad   110          112       10
9    335986        2        Kolkata Knight Riders   112          114        5

In [19]:
# Cell 3 — Find the highest-scoring innings

query = """
SELECT
    match_id,
    innings,
    batting_team,
    SUM(total_runs) AS runs
FROM v_ball
GROUP BY match_id, innings, batting_team
ORDER BY runs DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, con)
df

   match_id  innings                 batting_team  runs
0   1426268        1          Sunrisers Hyderabad   287
1   1473439        1          Sunrisers Hyderabad   286
2   1473505        1          Sunrisers Hyderabad   278
3   1422126        1          Sunrisers Hyderabad   277
4   1422134        1        Kolkata Knight Riders   272
5   1426273        1          Sunrisers Hyderabad   266
6   1529278        2                 Punjab Kings   265
7   1529278        1               Delhi Capitals   264
8    598027        1  Royal Challengers Bangalore   263
9   1426268        2  Royal Challengers Bangalore   262

In [20]:
# Cell 4 — Find average innings score

query = """
SELECT ROUND(AVG(runs), 2) AS average_score
FROM (
    SELECT
        match_id,
        innings,
        batting_team,
        SUM(total_runs) AS runs
    FROM v_ball
    GROUP BY match_id, innings, batting_team
);
"""

df = pd.read_sql_query(query, con)
df

   average_score
0         161.13

In [21]:
# Cell 5 — Find total runs scored by each team

query = """
SELECT
    batting_team,
    SUM(total_runs) AS total_runs
FROM v_ball
GROUP BY batting_team
ORDER BY total_runs DESC;
"""

df = pd.read_sql_query(query, con)
df

                   batting_team  total_runs
0                Mumbai Indians       46517
1           Sunrisers Hyderabad       44948
2   Royal Challengers Bangalore       44890
3                  Punjab Kings       44352
4                Delhi Capitals       43297
5           Chennai Super Kings       42557
6         Kolkata Knight Riders       42540
7              Rajasthan Royals       39159
8                Gujarat Titans       12196
9          Lucknow Super Giants       11509
10                Pune Warriors        6358
11                Gujarat Lions        4856
12       Rising Pune Supergiant        4533
13         Kochi Tuskers Kerala        1901

In [22]:
# Cell 6 — Find average score of each team

query = """
SELECT
    batting_team,
    ROUND(AVG(runs), 2) AS average_score
FROM (
    SELECT
        match_id,
        innings,
        batting_team,
        SUM(total_runs) AS runs
    FROM v_ball
    GROUP BY match_id, innings, batting_team
)
GROUP BY batting_team
ORDER BY average_score DESC;
"""

df = pd.read_sql_query(query, con)
df

                   batting_team  average_score
0                Gujarat Titans         176.75
1          Lucknow Super Giants         174.38
2           Chennai Super Kings         164.31
3                  Punjab Kings         163.66
4                Mumbai Indians         163.22
5                 Gujarat Lions         161.87
6           Sunrisers Hyderabad         161.10
7   Royal Challengers Bangalore         160.90
8              Rajasthan Royals         160.49
9                Delhi Capitals         157.44
10        Kolkata Knight Riders         156.40
11       Rising Pune Supergiant         151.10
12                Pune Warriors         141.29
13         Kochi Tuskers Kerala         135.79

In [23]:
# Cell 7 — Find teams with average score above 160

query = """
SELECT
    batting_team,
    ROUND(AVG(runs), 2) AS average_score
FROM (
    SELECT
        match_id,
        innings,
        batting_team,
        SUM(total_runs) AS runs
    FROM v_ball
    GROUP BY match_id, innings, batting_team
)
GROUP BY batting_team
HAVING AVG(runs) > 160
ORDER BY average_score DESC;
"""

df = pd.read_sql_query(query, con)
df

                  batting_team  average_score
0               Gujarat Titans         176.75
1         Lucknow Super Giants         174.38
2          Chennai Super Kings         164.31
3                 Punjab Kings         163.66
4               Mumbai Indians         163.22
5                Gujarat Lions         161.87
6          Sunrisers Hyderabad         161.10
7  Royal Challengers Bangalore         160.90
8             Rajasthan Royals         160.49

In [24]:
# Cell 8 — Find the highest-scoring team innings

query = """
SELECT
    batting_team,
    MAX(runs) AS highest_score
FROM (
    SELECT
        match_id,
        innings,
        batting_team,
        SUM(total_runs) AS runs
    FROM v_ball
    GROUP BY match_id, innings, batting_team
)
GROUP BY batting_team
ORDER BY highest_score DESC;
"""

df = pd.read_sql_query(query, con)
df

                   batting_team  highest_score
0           Sunrisers Hyderabad            287
1         Kolkata Knight Riders            272
2                  Punjab Kings            265
3                Delhi Capitals            264
4   Royal Challengers Bangalore            263
5          Lucknow Super Giants            257
6                Mumbai Indians            247
7           Chennai Super Kings            246
8              Rajasthan Royals            242
9                Gujarat Titans            233
10                Gujarat Lions            208
11       Rising Pune Supergiant            195
12                Pune Warriors            192
13         Kochi Tuskers Kerala            184

In [25]:
# Cell 9 — Count innings played by each team

query = """
SELECT
    batting_team,
    COUNT(*) AS innings_count
FROM (
    SELECT
        match_id,
        innings,
        batting_team
    FROM v_ball
    GROUP BY match_id, innings, batting_team
)
GROUP BY batting_team
ORDER BY innings_count DESC;
"""

df = pd.read_sql_query(query, con)
df

                   batting_team  innings_count
0                Mumbai Indians            285
1           Sunrisers Hyderabad            279
2   Royal Challengers Bangalore            279
3                Delhi Capitals            275
4         Kolkata Knight Riders            272
5                  Punjab Kings            271
6           Chennai Super Kings            259
7              Rajasthan Royals            244
8                Gujarat Titans             69
9          Lucknow Super Giants             66
10                Pune Warriors             45
11       Rising Pune Supergiant             30
12                Gujarat Lions             30
13         Kochi Tuskers Kerala             14

In [26]:
# Cell 10 — Find matches where the first innings score was above 200

query = """
WITH innings_scores AS (
    SELECT
        match_id,
        innings,
        batting_team,
        SUM(total_runs) AS runs
    FROM v_ball
    GROUP BY match_id, innings, batting_team
)
SELECT
    i.match_id,
    i.runs AS first_innings_runs,
    i.batting_team AS bat_first_team,
    m.match_winner
FROM innings_scores i
LEFT JOIN v_matches_clean m
    ON i.match_id = m.match_id
WHERE i.innings = 1
  AND i.runs > 200
ORDER BY i.runs DESC;
"""

df = pd.read_sql_query(query, con)
df

,match_id,first_innings_runs,bat_first_team,match_winner
0,1426268,287,Sunrisers Hyderabad,Sunrisers Hyderabad
1,1473439,286,Sunrisers Hyderabad,Sunrisers Hyderabad
2,1473505,278,Sunrisers Hyderabad,Sunrisers Hyderabad
3,1422126,277,Sunrisers Hyderabad,Sunrisers Hyderabad
4,1422134,272,Kolkata Knight Riders,Kolkata Knight Riders
...,...,...,...,...
186,1216547,201,Royal Challengers Bangalore,Mumbai Indians
187,1426288,201,Sunrisers Hyderabad,Sunrisers Hyderabad
188,1473481,201,Punjab Kings,Kolkata Knight Riders
189,1527674,201,Sunrisers Hyderabad,Royal Challengers Bangalore
190,1527689,201,Royal Challengers Bangalore,Rajasthan Royals

In [27]:
# Cell 11 — Find the biggest first-innings score

query = """
SELECT
    MAX(runs) AS highest_first_innings_score
FROM (
    SELECT
        match_id,
        SUM(total_runs) AS runs
    FROM v_ball
    WHERE innings = 1
    GROUP BY match_id, innings
);
"""

df = pd.read_sql_query(query, con)
df

   highest_first_innings_score
0                          287

In [28]:
# Cell 12 — Count wins by team

query = """
SELECT
    match_winner,
    COUNT(*) AS wins
FROM v_matches_clean
WHERE match_winner IS NOT NULL
GROUP BY match_winner
ORDER BY wins DESC;
"""

df = pd.read_sql_query(query, con)
df

                   match_winner  wins
0                Mumbai Indians   155
1           Chennai Super Kings   146
2   Royal Challengers Bangalore   139
3         Kolkata Knight Riders   137
4           Sunrisers Hyderabad   132
5                  Punjab Kings   130
6                Delhi Capitals   126
7              Rajasthan Royals   125
8                Gujarat Titans    42
9          Lucknow Super Giants    33
10       Rising Pune Supergiant    15
11                Pune Warriors    13
12                Gujarat Lions    13
13         Kochi Tuskers Kerala     6

In [29]:
# Cell 13 — Calculate chase-win percentage

query = """
WITH innings_scores AS (
    SELECT
        match_id,
        innings,
        batting_team,
        SUM(total_runs) AS runs
    FROM v_ball
    GROUP BY match_id, innings, batting_team
),
match_scores AS (
    SELECT
        match_id,
        MAX(CASE WHEN innings = 1 THEN batting_team END) AS first_team,
        MAX(CASE WHEN innings = 2 THEN batting_team END) AS chasing_team
    FROM innings_scores
    GROUP BY match_id
)
SELECT
    ROUND(
        100.0 * AVG(
            CASE
                WHEN m.match_winner = s.chasing_team THEN 1.0
                ELSE 0.0
            END
        ),
        2
    ) AS chase_win_percentage
FROM match_scores s
JOIN v_matches_clean m
    ON s.match_id = m.match_id
WHERE s.chasing_team IS NOT NULL
  AND m.match_winner IS NOT NULL;
"""

df = pd.read_sql_query(query, con)
df

   chase_win_percentage
0                 54.73

In [30]:
# Cell 14 — Find the best venues for chasing

query = """
WITH innings_scores AS (
    SELECT
        match_id,
        innings,
        batting_team,
        SUM(total_runs) AS runs
    FROM v_ball
    GROUP BY match_id, innings, batting_team
),
match_scores AS (
    SELECT
        match_id,
        MAX(CASE WHEN innings = 2 THEN batting_team END) AS chasing_team
    FROM innings_scores
    GROUP BY match_id
)
SELECT
    m.venue_clean,
    COUNT(*) AS matches,
    ROUND(
        100.0 * AVG(
            CASE
                WHEN m.match_winner = s.chasing_team THEN 1.0
                ELSE 0.0
            END
        ),
        2
    ) AS chase_win_percentage
FROM match_scores s
JOIN v_matches_clean m
    ON s.match_id = m.match_id
WHERE s.chasing_team IS NOT NULL
  AND m.match_winner IS NOT NULL
GROUP BY m.venue_clean
HAVING COUNT(*) >= 30
ORDER BY chase_win_percentage DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, con)
df

                           venue_clean  matches  chase_win_percentage
0               Sawai Mansingh Stadium       66                 65.15
1                         Eden Gardens      103                 58.25
2   Punjab Cricket Association Stadium       35                 57.14
3                     Wankhede Stadium      130                 55.38
4                M Chinnaswamy Stadium      103                 55.34
5   Rajiv Gandhi International Stadium       86                 54.65
6  Dubai International Cricket Stadium       46                 54.35
7                     Feroz Shah Kotla       59                 54.24
8           Dr DY Patil Sports Academy       37                 54.05
9                Narendra Modi Stadium       37                 51.35

In [31]:
# Cell 15 — Find runs scored in each innings phase

query = """
SELECT
    phase,
    SUM(total_runs) AS total_runs
FROM v_ball
GROUP BY phase
ORDER BY total_runs DESC;
"""

df = pd.read_sql_query(query, con)
df

       phase  total_runs
0     Middle      169160
1  Powerplay      116397
2      Death      104056